

 ---------------------------------------------
 Run case  1:   case_01_01

 alpha        ->  CL       =   1.289        
 beta         ->  beta        =   0.0
 pb/2V        ->  pb/2V       =   0.0
 qc/2V        ->  qc/2V       =   0.0
 rb/2V        ->  rb/2V       =   0.00000
 flap         ->  flap        =   0.00000
 aileron      ->  Cl roll mom =   0.00000
 elevator     ->  Cm pitchmom =   0.00000

 DVjet        ->  DVjet       =   1.00000

 alpha     =   0.00000     deg
 beta      =   0.00000     deg
 pb/2V     =   0.0
 qc/2V     =   0.0
 rb/2V     =   0.00000
 CL        =   1.2890036518026065                        
 CDo       =   0.0
 bank      =   0.00000     deg
 elevation =   0.00000     deg
 heading   =   0.00000     deg
 Mach      =   0.2229
 velocity  =   0.0     m/s               
 density   =   1.225     kg/m^3
 grav.acc. =   9.81     m/s^2
 turn_rad. =   0.00000     m
 load_fac. =   1.0
 X_cg      =   19.09095395290187     m
 Y_cg      =   0.0     m
 Z_cg      =   -0.93234881359062     m
 mass      =   70082.2662101167     kg
 Ixx       =   18232.68196159369     kg-m^2
 Iyy       =   1904458.8587356517     kg-m^2
 Izz       =   1895726.383100552     kg-m^2
 Ixy       =   572.7849241460908     kg-m^2
 Iyz       =   -9559.236570107843     kg-m^2
 Izx       =   -13736.554809208872     kg-m^2
 visc CL_a =   0.00000
 visc CL_u =   0.00000
 visc CM_a =   0.00000
 visc CM_u =   0.00000

