

 ---------------------------------------------
 Run case  1:   case_01_01

 alpha        ->  CL       =   1.9323        
 beta         ->  beta        =   0.0
 pb/2V        ->  pb/2V       =   0.0
 qc/2V        ->  qc/2V       =   0.0
 rb/2V        ->  rb/2V       =   0.00000
 flap         ->  flap        =   0.00000
 aileron      ->  Cl roll mom =   0.00000
 elevator     ->  Cm pitchmom =   0.00000

 alpha     =   0.00000     deg
 beta      =   0.00000     deg
 pb/2V     =   0.0
 qc/2V     =   0.0
 rb/2V     =   0.00000
 CL        =   1.9323048546329364                        
 CDo       =   0.0
 bank      =   0.00000     deg
 elevation =   0.00000     deg
 heading   =   0.00000     deg
 Mach      =   0.2
 velocity  =   0.0     m/s               
 density   =   1.225     kg/m^3
 grav.acc. =   9.81     m/s^2
 turn_rad. =   0.00000     m
 load_fac. =   1.0
 X_cg      =   18.416974673470325     m
 Y_cg      =   0.0     m
 Z_cg      =   -0.93234881359062     m
 mass      =   63864.46875258918     kg
 Ixx       =   13402.532398495105     kg-m^2
 Iyy       =   723318.2778211202     kg-m^2
 Izz       =   716982.3374972105     kg-m^2
 Ixy       =   1766.6480186467752     kg-m^2
 Iyz       =   -6619.830462678449     kg-m^2
 Izx       =   -8386.478481324377     kg-m^2
 visc CL_a =   0.00000
 visc CL_u =   0.00000
 visc CM_a =   0.00000
 visc CM_u =   0.00000

