

 ---------------------------------------------
 Run case  1:   case_01_01

 alpha        ->  CL       =   0.4997        
 beta         ->  beta        =   0.0
 pb/2V        ->  pb/2V       =   0.0
 qc/2V        ->  qc/2V       =   0.0
 rb/2V        ->  rb/2V       =   0.00000
 flap         ->  flap        =   0.00000
 aileron      ->  Cl roll mom =   0.00000
 elevator     ->  Cm pitchmom =   0.00000

 DVjet        ->  DVjet       =   1.00000

 alpha     =   0.00000     deg
 beta      =   0.00000     deg
 pb/2V     =   0.0
 qc/2V     =   0.0
 rb/2V     =   0.00000
 CL        =   0.49972067448756924                        
 CDo       =   0.0
 bank      =   0.00000     deg
 elevation =   0.00000     deg
 heading   =   0.00000     deg
 Mach      =   0.43
 velocity  =   0.0     m/s               
 density   =   0.6531     kg/m^3
 grav.acc. =   9.81     m/s^2
 turn_rad. =   0.00000     m
 load_fac. =   1.0
 X_cg      =   11.719641823017357     m
 Y_cg      =   0.0     m
 Z_cg      =   1.385     m
 mass      =   21630.042646446345     kg
 Ixx       =   27602.06267677713     kg-m^2
 Iyy       =   182588.30308507185     kg-m^2
 Izz       =   168657.41300734144     kg-m^2
 Ixy       =   3417.793149761545     kg-m^2
 Iyz       =   13202.671672784576     kg-m^2
 Izx       =   9784.87852302275     kg-m^2
 visc CL_a =   0.00000
 visc CL_u =   0.00000
 visc CM_a =   0.00000
 visc CM_u =   0.00000

