

 ---------------------------------------------
 Run case  1:   case_01_01

 alpha        ->  CL          =   0.4587        
 beta         ->  beta        =   0.0
 pb/2V        ->  pb/2V       =   0.0
 qc/2V        ->  qc/2V       =   0.0
 rb/2V        ->  rb/2V       =   0.00000
 elevator     ->  Cm pitchmom =   0.00000

 alpha     =   0.00000     deg
 beta      =   0.00000     deg
 pb/2V     =   0.0
 qc/2V     =   0.0
 rb/2V     =   0.00000
 CL        =   0.00000                        
 CDo       =   0.0
 bank      =   0.00000     deg
 elevation =   0.00000     deg
 heading   =   0.00000     deg
 Mach      =   0.7
 velocity  =   0.0     m/s               
 density   =   0.3805     kg/m^3
 grav.acc. =   9.81     m/s^2
 turn_rad. =   0.00000     m
 load_fac. =   1.0
 X_cg      =   11.897364385640293     m
 Y_cg      =   0.0     m
 Z_cg      =   1.385     m
 mass      =   26186.297199134595     kg
 Ixx       =   63891.62825499781     kg-m^2
 Iyy       =   218837.27283902987     kg-m^2
 Izz       =   231826.8342006888     kg-m^2
 Ixy       =   8598.554101862997     kg-m^2
 Iyz       =   18983.04532075779     kg-m^2
 Izx       =   10384.491218894927     kg-m^2
 visc CL_a =   0.00000
 visc CL_u =   0.00000
 visc CM_a =   0.00000
 visc CM_u =   0.00000

