c
c---- dot-pattern masks for use with plgrid, newpat, etc.
c
c    lmask0:  _________________________   (solid)
c         1:  .........................
c         2:  . . . . . . . . . . . . .
c         3:  .   .   .   .   .   .   .
c         4:  .       .       .       .
c
      data  lmask0,  lmask1,  lmask2,  lmask3,  lmask4
     &   / -1     ,  -21846,  -30584,  -32640,  -32768 /
c
c      data  lmask0,      lmask1,      lmask2,      lmask3,      lmask4
c     &   /Z'FFFFFFFF',Z'AAAAAAAA',Z'CCCCCCCC',Z'88888888',Z'21084210'/

